apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: json-server
  template:
    metadata:
      labels:
        app: json-server
    spec:
      containers:
      - name: json-server
        image: clue/json-server-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
