apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hitmanamine/Projetfederateur.git'  # Vérifie bien cette URL !
    targetRevision: main
    path: 'charts/mychart'  # Assure-toi que le chemin est bon
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
