version: '3.6'

services:
  elasticsearch_elk:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch_elk
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
    networks:
      - elk_network
    mem_limit: 2g

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xmx512m -Xms512m
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    networks:
      - elk_network
    depends_on:
      - elasticsearch_elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_elk:9200
    ports:
      - "5601:5601"
    networks:
      - elk_network
    depends_on:
      - elasticsearch_elk

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_logs:/var/log/nginx
    restart: on-failure
    networks:
      - elk_network
    depends_on:
      - kibana

volumes:
  esdata:
    driver: local

networks:
  elk_network:
    driver: bridge
