name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Minikube
        run: |
          # Installer Minikube
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo chmod +x minikube
          sudo mv minikube /usr/local/bin/

          # Lancer Minikube avec Docker comme driver
          minikube start --driver=docker

      - name: Set up Helm
        run: |
          # Installer Helm
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy with Helm
        run: |
          # Déployer Prometheus avec Helm
          kubectl create namespace monitoring || true
          helm upgrade --install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring
